### DISCUSSION TITLE
How to change the config ?

### DISCUSSION THREAD

**Discussion by geriwald** [jesseduffield/lazydocker#494] [Q&A]
This may be a bug, but it may be a chair/keyboard interface problem.

I want to change the lazydocker config, specifically the logs parameter.

Depending on how i view the config, i have three different parameters.

In my config file /home/prod/.config/lazydocker/config.yml I have : 
```
logs:
  timestamps: false
  since: '' # set to '' to show all logs
  tail: 200 # set to 200 to show last 200 lines of logs
```
This file's permissions seem ok : 
```
.rw-r--r-- 2.0k prod 25 Oct 13:27 config.yml
```
In lazydocker / Project / about I have :  
```
logs:
  timestamps: false
  since: ""
```
but when I press 'e' I am editing the config.yml file

With lazydocker --config I have : 
```
logs:
  since: 60m
```
When I select a docker with a lot of logs, I have to wait for ALL the logs to show, no time limit, no lines limit.

I'm running lazydocker on a debian server via a ssh connection.
