### DISCUSSION TITLE
Custom Commands

### DISCUSSION THREAD

**Discussion by josephcrawfordSRH** [jesseduffield/lazydocker#660] [Q&A]
I copied the default config from the repo and put it in place on my system.  I created a new custom command but when I go into LazyDocker and select a container I hit c I only see `cancel`. 

I do not see any of the defined custom commands, what could I be doing wrong?

**Comment by ShreeChaturvedi** [comment]
`c` on a container only lists `customCommands.containers`. The bundled default for that list is empty, so the menu is just cancel until something is under that key.

It has to live in the user config (Linux: `~/.config/lazydocker/config.yml`), nested like this, then restart lazydocker:

```yaml
customCommands:
  containers:
    - name: bash
      attach: true
      command: 'docker exec -it {{ .Container.ID }} bash'
      serviceNames: []
```

Open the loaded file from the project panel with `o` if you're not sure which one is in use. Commands under `services` or `images` only show in those panels. A non-empty `serviceNames` list hides the command on other containers.
