### ISSUE TITLE
Add docker-compose build to Services

### ISSUE THREAD

**Issue by mcintyre94** [jesseduffield/lazydocker#161]
**Is your feature request related to a problem? Please describe.**

If we're testing using docker-compose and we change a single image (eg. a test or an API call), then to re-build just that image we need to leave lazydocker. We can bulk build, but that's wasteful and hard to read the output of even if it uses cache for all the other images.

**Describe the solution you'd like**

A new menu option under 'x' for Services to build. When chosen it'd do `{DOCKER COMPOSE COMMAND} build {IMAGE}`

**Describe alternatives you've considered**

- Use bulk build command (slower, too much output)
- Exit lazydocker and re-build (`using docker-compose build image`), then use lazydocker to re-run

**Additional context**

More of an open question around keyboard shortcut because 'b' is used for the bulk menu. Maybe 'B' is OK or we just use a different letter?

**Comment by dawidd6** [comment]
I think that it can be already achieved with custom commands.

For example:
```yaml
# config.yml
customCommands:
  services:
    - name: rebuild service
      attach: true
      command: '{{ .DockerCompose }} build {{ .Service.Name }}'
```

Dunno tho if you meant service instead of image, but according to `docker-compose build --help` the argument should be a service name.

[![asciicast](https://asciinema.org/a/dt9PRs3MdcIPGShtCeff1ObC1.svg)](https://asciinema.org/a/dt9PRs3MdcIPGShtCeff1ObC1)
