### ISSUE TITLE
Logs tab is always empty

### ISSUE THREAD

**Issue by benjamin-feron** [jesseduffield/lazydocker#218]
**Describe the bug**
The Logs tab is empty for each containers but when I press "m" key, logs appears as well.

**To Reproduce**
1. Launch lazydocker
2. Navigate in different containers -> Logs tab is still empty
3. Press "m" key -> GUI disappears, logs are shown
4. Press Ctrl+c -> GUI re-appears, Logs tab is still empty

**Expected behaviour**
Logs tab should display content !

**Desktop (please complete the following information):**
 - OS: Debian Stretch
 - Lazydocker Version: docker image lazyteam/lazydocker:version-0.9.1

**docker-compose.yml**
```yml
version: '3'
services:
  lazydocker:
    container_name: lazydocker
    image: lazyteam/lazydocker:version-0.9.1
    build:
      context: https://github.com/jesseduffield/lazydocker.git
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/local/lazydocker/:/.config/jesseduffield/lazydocker
    restart: always
```

**Comment by benjamin-feron** [comment]
docker-compose.yml

```yml
version: '3'
services:
  lazydocker:
    container_name: si-lazydocker
    image: lazyteam/lazydocker:version-0.8
    build:
      context: https://github.com/jesseduffield/lazydocker.git
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/local/lazydocker/:/.config/jesseduffield/lazydocker
    restart: always
```
