### ISSUE TITLE
define own custom command

### ISSUE THREAD

**Issue by StephanKrauss** [jesseduffield/lazydocker#227]
Hello,

i work with docker under windows 10 and dockerdesktop.
I have a simple question.
Can i define my docker commands ?

Your sincerly

Stephan Krauß

**Comment by stokito** [comment]
yes, press `c` or menu `x` / `Run predefined custom command`.
Currently there is only login to container's shell but you can add any your command.
Open config by pressing `o` and then add to it's end:

```
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
  - name: Your new custom command
    attach: true
    command: docker top {{ .Container.ID }}
    serviceNames: []
```
