### ISSUE TITLE
Highlight items - contrast

### ISSUE THREAD

**Issue by mhagnumdw** [jesseduffield/lazydocker#243]
Hi!

Is it possible to increase the contrast of the selected item?

### Containers tab

![image](https://user-images.githubusercontent.com/17688846/99188731-53a86d00-273c-11eb-988e-6ef73c4d7bbd.png)

### Images tab

![image](https://user-images.githubusercontent.com/17688846/99188761-70dd3b80-273c-11eb-8caf-9664b120c996.png)

### Menu

![image](https://user-images.githubusercontent.com/17688846/99188789-966a4500-273c-11eb-9db1-f41483aa35b1.png)

### Versions
- Windows 10 + WSL 2
- Ubuntu 20.04

### lazydocker --version

```
Version: 0.10
Date: 2020-11-13T02:54:35Z
BuildSource: binaryRelease
Commit: ff0a53bfadfb1bfef5a0e3db023d57fed36fe4eb
OS: linux
Arch: amd64
```

### lazydocker --config

<details>
  <summary>Click to expand!</summary>

```
gui:
  scrollHeight: 2
  theme:
    activeBorderColor:
    - green
    - bold
    inactiveBorderColor:
    - default
    optionsTextColor:
    - blue
reporting: undetermined
commandTemplates:
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  dockerCompose: docker-compose
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  viewContainerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID
    }}
  containerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID }}
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
bulkCommands:
  services:
  - name: up
    attach: false
    command: '{{ .DockerCompose }} up -d'
    serviceNames: []
  - name: up (attached)
    attach: true
    command: '{{ .DockerCompose }} up'
    serviceNames: []
  - name: stop
    attach: false
    command: '{{ .DockerCompose }} stop'
    serviceNames: []
  - name: pull
    attach: true
    command: '{{ .DockerCompose }} pull'
    serviceNames: []
  - name: build
    attach: true
    command: '{{ .DockerCompose }} build --parallel --force-rm'
    serviceNames: []
  - name: down
    attach: false
    command: '{{ .DockerCompose }} down'
    serviceNames: []
  - name: down with volumes
    attach: false
    command: '{{ .DockerCompose }} down --volumes'
    serviceNames: []
  - name: down with images
    attach: false
    command: '{{ .DockerCompose }} down --rmi all'
    serviceNames: []
  - name: down with volumes and images
    attach: false
    command: '{{ .DockerCompose }} down --volumes --rmi all'
    serviceNames: []
oS:
  openCommand: sh -c "xdg-open {{filename}} >/dev/null"
  openLinkCommand: sh -c "xdg-open {{link}} >/dev/null"
update:
  dockerRefreshInterval: 100ms
stats:
  graphs:
  - caption: CPU (%)
    statPath: DerivedStats.CPUPercentage
    color: cyan
  - caption: Memory (%)
    statPath: DerivedStats.MemoryPercentage
    color: green
  maxDuration: 3m0s
```  
</details>
