### ISSUE TITLE
Question: save containers' logs

### ISSUE THREAD

**Issue by perezzini** [jesseduffield/lazydocker#303]
Hi,

Simple question. Is there any way, through a keybinding, to download/save a container's current logs?

Thanks in advance!

**Comment by eruizc-dev** [comment]
I feel that's a more docker thing than a lazydocker one. You can always dump logs with `docker container logs <id> >> /tmp/dump.log 2>&1`. You can also try this custom config (I have not tried it, so it might need some adjustments)

```yml
customCommands:
  containers:
    - name: dump logs
      prompts:
        - type: 'input'
          title: 'Provide a filename'
    command: "docker container logs '{{ .Container.ID }}' >> '{{index .PromptResponses 0}}' 2>&1"
```
