### ISSUE TITLE
Change selected background color like lazygit

### ISSUE THREAD

**Issue by hnbnh** [jesseduffield/lazydocker#393]
**Is your feature request related to a problem? Please describe.**
Is there any options to change the selected background color? The default color looks bad in my terminal.

**Describe the solution you'd like**
Have a option like `lazygit`:
```yml
gui:
  theme:
    selectedLineBgColor:
      - default
```

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/30380682/197507301-d40644e7-d146-42a8-b7ad-99ac86a5018e.png)
