### ISSUE TITLE
Allow changing the default screen mode

### ISSUE THREAD

**Issue by Rdkang** [jesseduffield/lazydocker#400]
**Is your feature request related to a problem? Please describe.**
Most of the time i do not use the images and volumes panel and is unneeded information for me, So It would be great if i could set the default screen mode.

**Describe the solution you'd like**
An option in `config.yml`:
```yaml 
gui:
   # options should be: normal,half,fullscreen
   screenMode: "half"
   
```
**Describe alternatives you've considered**
An alternative improvement could be being able to toggle panels
