### ISSUE TITLE
Loading large logs of a service takes forever

### ISSUE THREAD

**Issue by birgersp** [jesseduffield/lazydocker#433]
**Describe the bug**
When selecting a Service to view a large log, loading of the log takes a very very long time. It sometimes takes several minutes to show anything.

In contrast, doing `docker logs -t --tail 1500 mycontainer 2>&1` for the container of the service, takes about 1 second to print out all 1500 lines.

**To Reproduce**
1. Run a service that emits a million lines to the log
2. Select the service
3. Wait
4. Growl annoyed, go to github.com/jesseduffield/lazydocker and file an issue

**Expected behaviour**
Logs should load immidiately

**Comment by birgersp** [comment]
I just noticed that some services actually doens't load at all. I suspect the "refresh" interval time is shorter than the time it takes to load the log.

FWIW this is my `~/.config/lazydocker/config.yaml`:

```
gui:
  returnImmediately: true
  expandFocusedSidePanel: true
logs:
  timestamps: true
  tail: 1000
```
