### ISSUE TITLE
Docker image missing 1.20-3.15

### ISSUE THREAD

**Issue by devregnfo** [jesseduffield/lazydocker#497]
I'm trying to figure out installing the Docker image.
I got this error building the image with docker
:
" => ERROR [internal] load metadata for docker.io/library/golang:1.20-alpine3.15 "

I went to the docker hub, to GOLANG as stated in the DOCKFILE, but that particular image and tag isn't found... only other setups.
Am I missing something? I'm completely new to this.

Thanks!

**Comment by turbcool** [comment]
Having same problem when trying to build docker image on an arm64 device. I'm going through steps in README.

**Comment by mark2185** [comment]
@turbcool does [this PR](https://github.com/jesseduffield/lazydocker/pull/495) help?

It bumps `ALPINE_VERSION` to `3.17`.

**Comment by turbcool** [comment]
> @turbcool does [this PR](https://github.com/jesseduffield/lazydocker/pull/495) help?
> 
> It bumps `ALPINE_VERSION` to `3.17`.

Yes, i successfully built lazydocker with this change.

**Comment by wolkenschieber** [comment]
For completeness here's a working compose-file for arm:
```yaml
---
version: '3'

services:
  lazydocker:
    build:
      context: https://github.com/jesseduffield/lazydocker.git
      args:
        ALPINE_VERSION: 3.19
        BASE_IMAGE_BUILDER: arm64v8/golang
        GOARCH: arm64
    platform: linux/arm64/v8
    image: lazyteam/lazydocker
    container_name: lazydocker
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/.config/jesseduffield/lazydocker
```
