### ISSUE TITLE
See empty/black screen when running lazydocker

### ISSUE THREAD

**Issue by maksimu** [jesseduffield/lazydocker#5]
After fresh/first time install of `lazydocker` on my Mac and running that command in the terminal (same in iTerm). I see a black screen from which I can't also exit out (Ctrl+C)

Here is the screen I see:
![image](https://user-images.githubusercontent.com/187306/60392575-c61e9b80-9aba-11e9-8fd5-f78850fab8e0.png)

Here are some things I could get out to try to debug:

```
➜  ~ lazydocker -v 
commit=1f6971e2ffcef09983ae9cf8134dce36a7ba7e63, build date=2019-06-30T02:16:45Z, build source=binaryRelease, version=0.2.1, os=darwin, arch=amd64
```

```
➜  ~ lazydocker -config
gui:
  scrollHeight: 2
  theme:
    activeBorderColor:
    - green
    - bold
    inactiveBorderColor:
    - white
    optionsTextColor:
    - blue
reporting: undetermined
commandTemplates:
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  dockerCompose: docker-compose
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  viewContainerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID
    }}
  containerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID }}
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
oS:
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}
update:
  method: never
stats:
  graphs:
  - caption: CPU (%)
    statPath: DerivedStats.CPUPercentage
    color: cyan
  - caption: Memory (%)
    statPath: DerivedStats.MemoryPercentage
    color: green
```

When running:
`lazydocker -debug`
I see the same black screen

```
➜  ~ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      ...
      ...
      System Integrity Protection: Enabled
      Time since boot: 19 days 22:12
```
