### ISSUE TITLE
Cannot proceed until docker gives us more information about the container. Please retry in a few moments. 

### ISSUE THREAD

**Issue by danielb2** [jesseduffield/lazydocker#521]
> Cannot proceed until docker gives us more information about the container. Please retry in a few moments. 

I'm getting this when viewing config for a particular container, but only when that container has been started via compose. 

For example, this particular container:
`running  nginx        0.00% 443->443/tcp, 80->80/tcp, :::443->443/tcp`

```
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /titan/docker/config/nginx:/config
    restart: unless-stopped
```
