### ISSUE TITLE
log section improvements

### ISSUE THREAD

**Issue by bugzpodder** [jesseduffield/lazydocker#53]
Love the tool!

I'd like to propose some potential small enhancements to the logs section:
1. filter by time (30s/5m/1hr) [maybe not that useful]
2. color coding [not too sure how to decide what needs to be color coded, perhaps part of config using regex]
3. Don't allow scroll pass the end of logs
3. regex search [this will be super useful i think]

**Comment by nicholascloud** [comment]
Ditto about loving the tool -- I would like to request an option to wrap long log lines.

**Comment by jesseduffield** [comment]
wrapping logs is possible via:
```
gui:
  wrapMainPanel: true
```

Filtering logs is also possible by overriding with:
```
commandTemplates:
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  containerLogs: docker logs --follow --since=60m {{ .Container.ID }}
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
```

Not scrolling past the end of logs is covered here: https://github.com/jesseduffield/lazydocker/issues/31

color coding sounds tricky, could you raise a separate issue for that?

searching is covered by https://github.com/jesseduffield/lazydocker/issues/33

I think that covers everything :)

**Comment by bugzpodder** [comment]
wow, thats amazing.  Thank you!

**Comment by nicholascloud** [comment]
@jesseduffield Ah, awesome.  Thanks for the reply!

Dropping this bit from the [config doc](https://godoc.org/github.com/jesseduffield/lazydocker/pkg/config) here just in case someone doesn't know how to edit their config.yml:

> You can open your config file by going to the status panel (using left-arrow) and pressing 'o'.

**Comment by thibault-ketterer** [comment]
works for colors but a bit slowish

```
commandTemplates:  
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }} | ccze -A'
  containerLogs: docker logs --follow --since=60m {{ .Container.ID }} | ccze -A                     
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow | ccze -A'

```
