### ISSUE TITLE
Human-readable formatting of large numbers

### ISSUE THREAD

**Issue by cowwoc** [jesseduffield/lazydocker#608]
**Is your feature request related to a problem? Please describe.**
The "stats" tab of a docker container contains many large numbers that are difficult to understand and parse. For example:

```
cpu_stats
  cpu_usage
    total_usage: 15579438000
    usage_in_kernelmode: 2341492000
    usage_in_usermode: 13237946000
memory_stats:
  limit: 157286400
```

**Describe the solution you'd like**
It would be helpful to format this for human consumption. For example, adding a separator every 3 digits would help.
Separately, it would be helpful to convert large number of bytes into MB or GB to make it easier to understand.

**Describe alternatives you've considered**
Copy/pasting numbers from the screen and breaking out a calculator, but this makes it very hard to quickly scan a container's stats.
