### ISSUE TITLE
Cannot see logs

### ISSUE THREAD

**Issue by TangMonk** [jesseduffield/lazydocker#614]
I set the lazydocker config: 

```
logs:
  timestamps: false
  tail: 100
  since: '10m'
```

But lazydocker show empty logs.

But I can check log in: `docker compose logs --tail 100 -f`
