### ISSUE TITLE
Allow custom bulk commands

### ISSUE THREAD

**Issue by nikhilweee** [jesseduffield/lazydocker#643]
**Is your feature request related to a problem? Please describe.**
I often find myself starting my services using `docker compose up --build`. It's great that lazydocker has support for custom commands, but I couldn't find a way to add custom bulk commands.

**Describe the solution you'd like**
It would be great if lazydocker adds support for custom bulk commands.

**Describe alternatives you've considered**
Exit lazydocker and manually type the commands in the terminal

**Additional context**
I tried adding the following in the `bulkCommands` section of the config:

```yaml
bulkCommands:
  services:
    - name: up (build)
      attach: false
      shell: false
      command: "{{ .DockerCompuse }} up -d --build"
      serviceNames: []
```

However that replaces all the bulk commands. A quick solution might be to append `bulkCommands` from user config to the default config as opposed to replacing them. Perhaps a more elegant solution would be to add another section in the user config for custom bulk commands.
