### ISSUE TITLE
support full customisation of colours

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazydocker#67]
**Is your feature request related to a problem? Please describe.**
Currently we use different colours in different parts of the app, and people will likely want to customise those.

**Describe the solution you'd like**
The schema would be something like this:
```
gui:
  theme:
    servicePanel:
      status:
        none: blue
        running: green
        exitedZero: yellow
        exitedNonZero: red
```

There will be quite a few keys here so working out the right schema shape may be tricky, and it's worth keeping in mind that these keys will be subject to change with changes in lazydocker version.

**Describe alternatives you've considered**
Not doing this

**Additional context**
N/A
